title: Introduction to Machine Learning # title which appears for the website
email: manas@umbc.edu #your-email@example.com
description: A Course on Introduction to Machine Learning 
# short discription of your website. It is helpful for making your website more discoverable and appears while previewing your website.
    
 
baseurl: "CMSC678_F23"   # specify the subpath of your site
url: "https://manasgaur.github.io" # the base hostname & protocol for YOUR site, e.g. http://example.com
twitter_username: #
github_username: #
theme: minima
plugins:
  - jekyll-feed